version: "3.8"
services:
#  jenkins: 
#    image: jenkins/jenkins:lts
#    privileged: true
#    user: mnaja
#    ports:
#     - 8081:8081
#     - 50000:50000
#    container_name: jenkins
#    volumes:
#    - /home/mnaja/Desktop/project:/var/jenkins_home
#    - /var/run/docker.sock:/var/run/docker.sock

  gitlab:
    image: 'alpinelinux/gitlab-runner'
    restart: always
    hostname: 'localhost'
    container_name: gitlab-ce
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '8083:83'
      - '8443:443'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab
  gitlabee-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlabee-runner
    volumes:
      - gitlab_home_runner_config:/home/gitlab-runner
      - gitlab_etc_runner_config:/etc/gitlab-runner
      
      - /var/run/docker.sock:/var/run/docker.sock
    
    restart: unless-stopped


    networks:
      - gitlab
volumes:
  gitlab_home_runner_config:
    # external: true // Specify if you wish to create and manage yourself
  gitlab_etc_runner_config:

#  sonarqube:
#    image: sonarqube:community
#    hostname: sonarqube
#    container_name: sonarqube
#    depends_on:
#      - db
#    environment:
#      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
#      SONAR_JDBC_USERNAME: sonar
#      SONAR_JDBC_PASSWORD: sonar
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_logs:/opt/sonarqube/logs
#    ports:
#      - "9000:9000"
#  db:
#    image: postgres:12
#    hostname: postgresql
#    container_name: postgresql
#    environment:
#      POSTGRES_USER: sonar
#      POSTGRES_PASSWORD: sonar
#      POSTGRES_DB: sonar
#    volumes:
#      - postgresql:/var/lib/postgresql
#      - postgresql_data:/var/lib/postgresql/data

#volumes:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#  postgresql:
#  postgresql_data:
#  nexus-data: {}
networks:
  gitlab:
    name: gitlab-network


#  nexus:
#    image: sonatype/nexus
#    volumes:
#      - "nexus-data:/sonatype-work"
#    ports:
#      - "8081:8081"
  



#volumes:
#  projects: